### ISSUE TITLE
melding does not work with latest meteor code

### ISSUE THREAD

**Issue by kaushik1979** [splendido/meteor-accounts-meld#24]
If I run 'meteor update', your test app stops working.

```
W20150904-12:11:41.189(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:41.191(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:41.191(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:41.191(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:41.191(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:41.192(-4)? (STDERR) 
W20150904-12:11:41.192(-4)? (STDERR) /Users/priyankasharma/.meteor/packages/meteor-tool/.1.1.4.js2pp6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150904-12:11:41.192(-4)? (STDERR) 						throw(ex);
W20150904-12:11:41.192(-4)? (STDERR) 						      ^
W20150904-12:11:41.192(-4)? (STDERR) ReferenceError: Router is not defined
W20150904-12:11:41.192(-4)? (STDERR)     at app/lib/router.js:1:36
W20150904-12:11:41.192(-4)? (STDERR)     at app/lib/router.js:26:3
W20150904-12:11:41.192(-4)? (STDERR)     at /Users/priyankasharma/Meteor/qoll/test-accounts-meld/.meteor/local/build/programs/server/boot.js:222:10
W20150904-12:11:41.192(-4)? (STDERR)     at Array.forEach (native)
W20150904-12:11:41.192(-4)? (STDERR)     at Function._.each._.forEach (/Users/priyankasharma/.meteor/packages/meteor-tool/.1.1.4.js2pp6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150904-12:11:41.192(-4)? (STDERR)     at /Users/priyankasharma/Meteor/qoll/test-accounts-meld/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
W20150904-12:11:44.458(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:44.458(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:44.458(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:44.458(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:44.458(-4)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!
W20150904-12:11:44.459(-4)? (STDERR) 
W20150904-12:11:44.460(-4)? (STDERR) /Users/priyankasharma/.meteor/packages/meteor-tool/.1.1.4.js2pp6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150904-12:11:44.460(-4)? (STDERR) 						throw(ex);
W20150904-12:11:44.460(-4)? (STDERR) 						      ^
W20150904-12:11:44.467(-4)? (STDERR) ReferenceError: Router is not defined
W20150904-12:11:44.467(-4)? (STDERR)     at app/lib/router.js:1:36
W20150904-12:11:44.468(-4)? (STDERR)     at app/lib/router.js:26:3
W20150904-12:11:44.468(-4)? (STDERR)     at /Users/priyankasharma/Meteor/qoll/test-accounts-meld/.meteor/local/build/programs/server/boot.js:222:10
W20150904-12:11:44.468(-4)? (STDERR)     at Array.forEach (native)
W20150904-12:11:44.468(-4)? (STDERR)     at Function._.each._.forEach (/Users/priyankasharma/.meteor/packages/meteor-tool/.1.1.4.js2pp6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150904-12:11:44.469(-4)? (STDERR)     at /Users/priyankasharma/Meteor/qoll/test-accounts-meld/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

**Comment by splendido** [comment]
This is not a problem with the latest version of Meteor nor with `splendido:accounts-meld`, but rather with the latest versions of `useraccounts` packages.
As the error says, you now need to add `useraccounts:iron-routing` to get the application routing layer work as before.

I've just updated the test application: see [this commit](https://github.com/splendido/test-accounts-meld/commit/f992e2379dc2d7bf42656b0bcf3d642e02c9b670)
