### ISSUE TITLE
Error When Using With Meteor.LoginWithMicrosoft (q42:accounts-microsoft)

### ISSUE THREAD

**Issue by breagan1983** [splendido/meteor-accounts-meld#38]
Not sure if this is part of the development roadmap; was testing use with q42's accounts-microsoft package...

Env: already logged into an account provisioned by .loginWithLinkedIn(); attempted .loginWithMicrosoft...client side it threw a 500 error, server side it thew a:

Exception while invoking method 'login' TypeError: Object [object Object] has no method 'map'

I20160115-13:47:50.696(-6)?     at getEmailsFromService (packages/splendido_accounts-emails-field/packages/splendido_accounts-emails-field.js:95:1)
I20160115-13:47:50.696(-6)?     at packages/splendido_accounts-emails-field/packages/splendido_accounts-emails-field.js:149:1
I20160115-13:47:50.697(-6)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160115-13:47:50.697(-6)?     at Object.updateEmails (packages/splendido_accounts-emails-field/packages/splendido_accounts-emails-field.js:142:1)
I20160115-13:47:50.697(-6)?     at AccountsServer.updateOrCreateUserFromExternalService (packages/splendido_accounts-meld/packages/splendido_accounts-meld.js:565:1)
I20160115-13:47:50.697(-6)?     at [object Object].Package (packages/accounts-oauth/oauth_server.js:55:1)
I20160115-13:47:50.697(-6)?     at accounts_server.js:462:32
I20160115-13:47:50.697(-6)?     at tryLoginMethod (accounts_server.js:239:14)
I20160115-13:47:50.697(-6)?     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
I20160115-13:47:50.697(-6)?     at [object Object].methods.login (accounts_server.js:522:27)

Haven't had a chance to dive into it much yet, but thought to throw this in the list in case anyone else was trying to make this work.  

Thanks for the awesome plugin; tremendously helpful for some of the Meteor apps I'm developing.

**Comment by breagan1983** [comment]
Also, forgot to mention - despite the error it's still working.  Plugin successfully melded the accounts, and am able to authenticate to the same account with the MS credentials.

**Comment by guidouil** [comment]
I am trying to setup the same package today (for Calendar Sync) and I get the following error 
```js
Exception while invoking method 'login' TypeError: emails.map is not a function
    at Object.getEmailsFromService (packages/splendido_accounts-emails-field.js:115:16)
    at AccountsServer.updateOrCreateUserFromExternalService (packages/splendido_accounts-meld.js:661:45)
    at [object Object].<anonymous> (packages/accounts-oauth.js:133:21)
    at packages/accounts-base/accounts_server.js:471:32
    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
    at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)
    at [object Object].methods.login (packages/accounts-base/accounts_server.js:531:27)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
```
I might wanna try a PR on this one 😄
