### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by xmarkclx** [splendido/meteor-accounts-meld#50]
I get an issue when using this and it's not working on my end (tested accounts-password and accounts-facebook accounts if they could meld, they don't):

I20170227-15:04:55.905(0)? Exception in onLogin callback: Error: After filtering out keys not in the schema, your modifier is now empty
I20170227-15:04:55.917(0)?     at [object Object].doValidate (packages/aldeed_collection2-core.js:416:11)
I20170227-15:04:55.920(0)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:214:25)
I20170227-15:04:55.924(0)?     at updateEmails (packages/splendido_accounts-emails-field.js:191:16)
I20170227-15:04:55.927(0)?     at runAndHandleExceptions (packages/callback-hook.js:152:24)
I20170227-15:04:55.931(0)?     at packages/callback-hook.js:159:12
I20170227-15:04:55.935(0)?     at packages/accounts-base/accounts_server.js:167:5
I20170227-15:04:55.938(0)?     at [object Object]._.extend.each (packages/callback-hook.js:128:15)
I20170227-15:04:55.942(0)?     at AccountsServer.Ap._successfulLogin (packages/accounts-base/accounts_server.js:166:21)
I20170227-15:04:55.945(0)?     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:356:10)
I20170227-15:04:55.948(0)?     at [object Object].methods.login (packages/accounts-base/accounts_server.js:533:21)
I20170227-15:05:12.045(0)? Exception in onLogin callback: Error: After filtering out keys not in the schema, your modifier is now empty
I20170227-15:05:12.046(0)?     at [object Object].doValidate (packages/aldeed_collection2-core.js:416:11)
I20170227-15:05:12.046(0)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:214:25)
I20170227-15:05:12.046(0)?     at updateEmails (packages/splendido_accounts-emails-field.js:191:16)
I20170227-15:05:12.047(0)?     at runAndHandleExceptions (packages/callback-hook.js:152:24)
I20170227-15:05:12.048(0)?     at packages/callback-hook.js:159:12
I20170227-15:05:12.048(0)?     at packages/accounts-base/accounts_server.js:167:5
I20170227-15:05:12.048(0)?     at [object Object]._.extend.each (packages/callback-hook.js:128:15)
I20170227-15:05:12.049(0)?     at AccountsServer.Ap._successfulLogin (packages/accounts-base/accounts_server.js:166:21)
I20170227-15:05:12.049(0)?     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:356:10)
I20170227-15:05:12.050(0)?     at [object Object].methods.login (packages/accounts-base/accounts_server.js:533:21)

**Comment by guidouil** [comment]
Works for me on Meteor 1.4.4.1 for now (also old school style project without import but with lot of npm pkgs...)
